import React, { createContext, useContext, useEffect, useState } from 'react';

export type Language = 'en' | 'hi';
type TranslationParams = Record<string, string | number>;

export const translations = {
  en: {
    home: "Home",
    orders: "Orders",
    products: "Products",
    customers: "Customers",
    profile: "Profile",
    active_partner: "Active Partner",
    logout: "Log Out",
    change_language: "Change Language",
    english: "English",
    hindi: "हिन्दी",
    greeting_morning: "Good morning",
    greeting_afternoon: "Good afternoon",
    greeting_evening: "Good evening",
    cat_fruits_vegetables: "Fruits & Vegetables",
    cat_bakery_bread: "Bakery & Bread",
    cat_dairy_eggs: "Dairy & Eggs",
    cat_beverages: "Beverages",
    cat_snacks_munchies: "Snacks & Munchies",
    cat_staples_atta: "Staples & Atta",
    cat_household_items: "Household Items",
    cat_personal_care: "Personal Care",
    today_sales: "Today's Sales",
    active_orders: "Active Orders",
    low_stock_alerts: "Low Stock Alerts",
    out_of_stock: "Out of Stock",
    store_status: "Store Status",
    open: "Open",
    closed: "Closed",
    placed: "Placed",
    shop_accepted: "Accepted",
    rider_assigned: "Rider Assigned",
    delivered: "Delivered",
    cancelled: "Cancelled",
    tab_new: "New",
    tab_preparing: "Preparing",
    tab_ready: "Ready",
    tab_completed: "Past",
    dispatch_order: "Dispatch Order",
    route_compat: "Locality Compatibility",
    recent_orders: "Recent Orders",
    sales_trend: "Sales Trend (Last 7 Days)",
    no_recent_orders: "No recent orders",
    all_items: "All Items",
    my_items: "My Items",
    add_product: "Add Product",
    search_items: "Search items...",
    edit_product: "Edit Product",
    edit: "Edit",
    save_changes: "Save Changes",
    cancel: "Cancel",
    name: "Product Name",
    category: "Category",
    price: "Sale Price (₹)",
    mrp: "MRP (₹)",
    stock: "Stock Level",
    description: "Description",
    image: "Image URL",
    upload: "Upload",
    delete: "Delete",
    order_id: "Order ID",
    items: "Items",
    delivery_address: "Delivery Address",
    instructions: "Instructions",
    accept: "Accept",
    reject: "Reject",
    mark_ready: "Mark Ready",
    no_orders: "No orders in this section",
    order_details: "Order Details",
    store_timings: "Store Timings",
    store_details: "Store Details",
    phone: "Phone",
    email: "Email",
    address: "Address",
    save_store_details: "Save Store Details",
    saving: "Saving...",
    total_spent: "Total Spent",
    customer_since: "Customer Since",
    no_customers: "No customers found.",
    loading_sessions: "Loading session credentials...",
    store_review_pending: "Store Review Pending",
    review_pending_message: "Your merchant profile is currently awaiting platform verification. You can configure your store catalog, timings and settings, but customer orders remain restricted until approval.",
    workspace_error_title: "We couldn’t open your workspace",
    workspace_error_desc: "Your data is safe. Refresh the app and try again.",
    refresh_app: "Refresh app",
    preparing_workspace: "Preparing your workspace",
    syncing_shop_data: "Securely syncing your shop data.",
    shop_partner: "Shop partner",
    shopkeeper_partner: "Shopkeeper Partner",
    notifications: "Store Notifications",
    no_notifications: "No new notifications",
    mark_all_read: "Mark all as read",
    analytics: "Analytics",
    inventory: "Inventory",
    reviews: "Reviews",
    offers: "Offers",
    login_title: "Kirana Partner Portal",
    login_subtitle: "Accept orders, manage inventory and grow your local sales.",
    signin_unavailable: "Sign-in unavailable",
    signin_unavailable_desc: "This app is missing its secure Firebase configuration. Please contact your administrator.",
    firebase_online: "Firebase Online",
    firebase_online_desc: "SMS codes will be sent securely via Google Firebase Authentication.",
    owner_mobile: "Owner Mobile Number",
    request_code: "Request OTP Code",
    requesting_code: "Requesting Code...",
    enter_otp: "Enter 6-Digit OTP Code",
    sms_sent_to: "Verification SMS sent to {{phone}}",
    back: "Back",
    verifying: "Verifying...",
    verify_continue: "Verify & Continue",
    login_agreement: "By logging in, you agree to the",
    merchant_terms: "Merchant Terms",
    privacy_policy: "Privacy Policy",
    and: "and",
    error_invalid_phone: "Please enter a valid 10-digit mobile number.",
    error_signin_not_configured: "Secure sign-in is not configured. Please contact support.",
    error_security_init: "Security verification could not be initialized. Refresh and try again.",
    otp_sent: "OTP code sent successfully to {{phone}}",
    error_send_otp: "Failed to send OTP. Please check your details.",
    error_sms: "Something went wrong while sending the SMS.",
    error_full_otp: "Please enter the complete 6-digit OTP code.",
    login_success: "Logged in successfully!",
    error_invalid_otp: "Invalid OTP code. Please try again.",
    error_verification: "Verification failed.",
    daily_target: "Daily target: ₹5,000",
    requires_action: "Requires action",
    manage_inventory: "Manage in Inventory",
    sales_progress: "Sales progress over the last 7 days",
    quick_refill: "Quick Inventory Refill",
    quick_refill_desc: "Replenish low-stock items with one-tap actions",
    quick_utilities: "Quick Access Utilities",
    view_orders: "View Orders",
    manage_catalog: "Manage Catalog",
    order_status_mix: "Order Status Mix",
    order_status_mix_desc: "Overview of store order fulfilment",
    latest_orders_desc: "Three latest customer orders",
    healthy_stock: "Healthy Stock",
    low_stock_alert: "Low Stock Alert",
    hidden_items: "Hidden Items",
    inventory_title: "Inventory Management",
    inventory_subtitle: "Track real-time stock levels, movement logs and adjustments",
    stock_correction: "Manual Stock Correction",
    stock_correction_desc: "Increase or decrease item stock instantly",
    select_product: "Select Product",
    choose_item: "Choose item...",
    correction_type: "Correction Type",
    quantity: "Quantity",
    correction_note: "Correction Note",
    correction_note_placeholder: "For example: fresh batch received or damaged box",
    stock_ledger: "Stock Ledger Reference",
    search_item: "Search item...",
    add_units: "Add {{count}} units",
    reduce_unit: "Reduce 1 unit",
    movement_logs: "Stock Movement & Adjustment Logs",
    movement_logs_desc: "Real-time audit history of product additions, purchases and refills",
    no_stock_logs: "No stock movements recorded yet.",
    restock: "Restock",
    sale: "Sale",
    return_stock: "Return",
    damaged: "Damaged",
    analytics_title: "Store Performance Analytics",
    analytics_subtitle: "Explore revenue, customers, average baskets and downloadable reports",
    monthly_sales: "Monthly Sales",
    weekly_sales: "Weekly Sales",
    average_order_value: "Average Order Value",
    customer_retention: "Customer Retention",
    sales_by_category: "Sales by Product Categories",
    sales_by_category_desc: "Revenue breakdown across major departments (₹)",
    peak_hours: "Peak Ordering Hours",
    peak_hours_desc: "Customer checkout frequency trends",
    top_products: "Top Selling Products",
    top_products_desc: "Highest-volume products in stock",
    slow_products: "Low Velocity Products",
    slow_products_desc: "Slowest-moving inventory items",
    download_report: "Download Report",
    no_data: "No data to display.",
    search_customers: "Search customers by name or phone...",
    last_purchase: "Last Purchase",
    favourites: "Favourites",
    vip: "VIP",
    shop_specials: "Shop specials",
    shop_specials_desc: "Reward loyal buyers, run public sales, add BOGO deals or publish a subscription plan.",
    no_specials: "No shop specials",
    no_specials_desc: "Create a sale, loyalty reward, BOGO deal or subscription plan.",
    create_special: "Create special",
    delete_special_confirm: "Delete this shop special permanently?",
    benefit: "Benefit",
    audience: "Audience",
    everyone: "Everyone",
    selected_customers: "Selected customers",
    create_shop_special: "Create shop special",
    offer_auto_apply: "The best eligible offer is applied automatically at checkout.",
    close: "Close",
    special_type: "Special type",
    title: "Title",
    minimum_order: "Minimum order",
    customer_description: "Customer-facing description",
    percentage: "Percentage",
    flat_amount: "Flat amount",
    free_delivery: "Free delivery",
    maximum_saving: "Maximum saving",
    customer_buys: "Customer buys",
    customer_gets_free: "Customer gets free",
    eligible_products: "Eligible products",
    select_loyal_customers: "Select loyal customers",
    customers_after_order: "Customers appear here after placing an order.",
    plan_price: "Plan price",
    billing_period: "Billing period",
    monthly: "Monthly",
    quarterly: "Quarterly",
    starts: "Starts",
    ends: "Ends",
    publish_special: "Publish special",
    public_sale: "Public sale",
    loyalty_reward: "Loyalty reward",
    bogo_deal: "Buy one, get one",
    subscription_plan: "Subscription plan",
    setup_store: "Set up your store",
    setup_subtitle: "Add accurate shop and inventory details before opening for customers.",
    step_shop: "Step 1 · Shop details",
    step_inventory: "Step 2 · Inventory",
    shop_logo: "Shop Logo",
    shop_cover: "Shop Cover Image",
    supported_images: "JPEG and PNG formats supported",
    shop_name: "Shop Name",
    owner_name: "Owner Name",
    owner_phone: "Owner Phone Number",
    shop_coordinates: "Shop Physical Coordinates",
    coordinates_desc: "Required for automatic distance calculations",
    detect_location: "Detect Current Location",
    detecting_location: "Detecting location...",
    latitude: "Latitude",
    longitude: "Longitude",
    gps_not_set: "GPS coordinates are not set. Tap detect location to use the shop’s live position.",
    customer_store_preview: "Live Store Card Customer View",
    continue_inventory: "Continue to Inventory Catalog Setup",
    product_cover: "Product cover image",
    tap_upload_cover: "Tap to upload cover",
    complete_setup: "Complete Setup & Open Shop",
    error_shop_details: "Please complete all shop details in Step 1.",
    error_add_product: "Please add at least one product with stock before opening your store.",
    error_location_required: "A valid GPS location is required. Please capture your shop location.",
    cancel_setup_confirm: "Cancel setup and log out?",
    error_shop_first: "Please complete the shop details first.",
    error_store_fields: "Please complete all required store details.",
    call_customer: "Call customer",
    whatsapp_customer: "Message customer on WhatsApp",
    delivery_location: "Delivery Location",
    reject_order: "Reject Order",
    reject_order_confirm: "Are you sure you want to reject this order?",
    selection: "Selection",
    select_rider: "Select Delivery Partner",
    rider_earnings: "Rider Earnings",
    estimated_route: "Estimated Route Travel",
    nearest_stop_order: "Nearest-stop order",
    batch_created: "Delivery batch created and assigned to {{name}}.",
    create_delivery_batch: "Create Delivery Batch",
    selected_orders: "Selected Orders",
    subtotal: "Subtotal",
    total: "Total",
    payment: "Payment",
    customer: "Customer",
    decrease_stock: "Decrease Stock",
    increase_stock: "Increase Stock",
    delete_product: "Delete Product",
    delete_product_confirm: "Delete this product permanently?",
    no_items_found: "No items found",
    product_main_image: "Product Main Image (Cover)",
    product_gallery: "Product Gallery Images",
    delete_image: "Delete image",
    store_availability: "Store Availability",
    store_availability_desc: "Open or close your store instantly",
    store_branding: "Store Branding",
    shop_logo_image: "Shop Logo Image",
    store_cover_banner: "Store Front Cover Banner",
    theme_style: "App Theme Style",
    theme_style_desc: "Choose Light (Day) or Dark (Night) mode",
    shop_parameters: "Shop Parameters",
    closing_time: "Closing Time",
    opening_time: "Opening Time",
    delivery_radius: "Delivery Radius (km)",
    legal_policies: "Legal & Policies",
    merchant_terms_conditions: "Merchant Terms & Conditions",
    merchant_privacy_policy: "Merchant Privacy Policy",
    customer_reviews: "Customer Reviews",
    reviews_subtitle: "Understand customer satisfaction, reply to reviews and manage ratings",
    no_reviews: "No Reviews Received",
    no_reviews_desc: "Customer reviews will appear here after completed orders.",
    report_review: "Report Fake Review",
    merchant_reply: "Merchant Reply",
    write_reply: "Write a response to this review...",
    reply: "Reply",
    reporting_reason: "Reason for Reporting",
    reporting_placeholder: "Fake rating, competitor abuse or profanity...",
    submit_report: "Submit Report",
    rating: "Rating",
    save: "Save",
    light: "Light",
    dark: "Dark",
    versus_last_month: "+8.2% vs last month",
    estimated_weekly_receipts: "Estimated weekly receipts",
    per_checkout: "Per checked-out cart",
    this_quarter: "+2.5% this quarter",
    complete_orders_for_insights: "Complete orders to see top-selling products.",
    units_checked_out: "{{count}} units checked out",
    catalog_moving_well: "All catalog items are moving well.",
    item_count: "{{count}} items",
    units_in_stock: "{{count}} in stock",
    units: "{{count}} units",
    add: "Add",
    reduce: "Reduce",
    quantity_example: "For example: 10",
    adjusting: "Adjusting...",
    execute_correction: "Execute Stock Correction",
    cannot_reduce_stock: "Cannot reduce stock by {{amount}}. Current stock is only {{stock}}.",
    manual_correction_note: "Manual inventory correction",
    updated_by: "By",
    public_sale_desc: "Percentage or flat discounts for every shopper.",
    loyalty_reward_desc: "A private recurring benefit for customers you select.",
    bogo_desc: "Buy-one-get-one and product-specific extras.",
    subscription_desc: "Publish a monthly or quarterly member plan.",
    offer_error_title: "Add a clear title and customer-facing description.",
    offer_error_date: "End date must be on or after the start date.",
    offer_error_percent: "Percentage discounts must be between 1% and 90%.",
    offer_error_flat: "Flat discount must be greater than ₹0.",
    offer_error_customer: "Select at least one loyal customer.",
    offer_error_product: "Select at least one product for the BOGO offer.",
    offer_error_subscription: "Subscription price cannot be negative.",
    offer_error_create: "Unable to create this shop special.",
    month: "month",
    quarter: "quarter",
    subscription_benefit: "₹{{price}}/{{period}} · {{value}}% member saving",
    percent_off: "{{value}}% off",
    percent_off_upto: "{{value}}% off up to ₹{{max}}",
    flat_off: "₹{{value}} off",
    buy_get_free: "Buy {{buy}}, get {{get}} free",
    active: "Active",
    expired: "Expired",
    paused: "Paused",
    shop_special: "Shop special",
    selected_count: "{{count}} selected",
    members: "Members",
    to: "to",
    offer_title_placeholder: "Weekend grocery sale",
    offer_desc_placeholder: "Save on your regular household essentials.",
    percent: "Percent",
    value: "Value",
    customer_order_spend: "{{orders}} orders · ₹{{spent}} spent",
    product_name_placeholder: "For example: Fresh Bread (400g)",
    product_desc_placeholder: "Product size, package and other details...",
    cat_groceries: "Groceries",
    cat_snacks_beverages: "Snacks & Beverages",
    cat_medical: "Medical / Pharmacy",
    cat_electronics: "Electronics",
    cat_stationery: "Stationery",
    cat_fashion: "Fashion",
    cat_books: "Books & Novelties",
    cat_home_essentials: "Home Essentials",
    cat_pet_supplies: "Pet Supplies",
    cat_beauty: "Beauty & Personal Care",
    geolocation_unsupported: "Location is not supported on this device.",
    price_above_mrp: "Selling price (₹{{price}}) cannot exceed MRP (₹{{mrp}}).",
    product_upload_failed: "Unable to upload the image for {{name}}. Please try again.",
    setup_failed: "Store setup failed: {{error}}",
    store_onboarding: "Store Onboarding",
    store_onboarding_desc: "Set up your store portal profile",
    step_one: "Step 1",
    step_two: "Step 2",
    add_inventory: "Add Inventory",
    provide_store_details: "Provide Store Profile Details",
    store_logo_banner: "Store Logo / Banner",
    tap_upload_store_logo: "Tap to upload store logo or banner",
    shop_name_placeholder: "For example: Fresh Choice Kirana",
    store_category: "Store Category Type",
    full_address: "Full Physical Address",
    address_placeholder: "For example: Shop No. 15, Ground Floor, Main Market",
    my_kirana_store: "My Kirana Store",
    store_location_address: "Store location address",
    add_initial_products: "Add Initial Products to Catalog",
    add_initial_products_desc: "Add at least one product and its stock count to enable customer checkout.",
    initial_product_placeholder: "For example: Farm Fresh Apples (1 kg)",
    price_example: "For example: 90",
    mrp_example: "For example: 100",
    initial_stock: "Initial Stock Count",
    stock_example: "For example: 50",
    calculated_discount: "Calculated customer discount: {{value}}% off MRP.",
    product_cover_optional: "Product Cover Image (Optional)",
    add_item_inventory: "Add Item to Inventory",
    added_catalog: "Added Catalog ({{count}})",
    no_initial_items: "No items added yet. Complete the form above to add a product.",
    return_dashboard: "Return to Dashboard",
    merchant_owner: "Merchant Owner",
    store_settings: "Store Settings",
    business_reports: "Business Reports",
    sign_out: "Sign Out",
    no_recent_alerts: "No recent alerts or notifications."
  },
  hi: {
    home: "मुख्य पृष्ठ",
    orders: "ऑर्डर सूची",
    products: "मेरे उत्पाद",
    customers: "ग्राहक",
    profile: "प्रोफ़ाइल",
    active_partner: "सक्रिय पार्टनर",
    logout: "लॉगआउट",
    change_language: "भाषा बदलें",
    english: "English",
    hindi: "हिन्दी",
    greeting_morning: "सुप्रभात",
    greeting_afternoon: "नमस्कार",
    greeting_evening: "शुभ संध्या",
    cat_fruits_vegetables: "फल और सब्जियां",
    cat_bakery_bread: "बेकरी और ब्रेड",
    cat_dairy_eggs: "डेयरी और अंडे",
    cat_beverages: "पेय पदार्थ",
    cat_snacks_munchies: "स्नैक्स और नमकीन",
    cat_staples_atta: "दालें और आटा",
    cat_household_items: "घरेलू सामान",
    cat_personal_care: "व्यक्तिगत देखभाल",
    today_sales: "आज की बिक्री",
    active_orders: "सक्रिय ऑर्डर",
    low_stock_alerts: "कम स्टॉक चेतावनी",
    out_of_stock: "स्टॉक समाप्त",
    store_status: "दुकान की स्थिति",
    open: "खुली है",
    closed: "बंद है",
    placed: "ऑर्डर प्राप्त",
    shop_accepted: "स्वीकार किया गया",
    rider_assigned: "राइडर असाइन किया गया",
    delivered: "वितरित",
    cancelled: "रद्द",
    tab_new: "नया",
    tab_preparing: "तैयारी",
    tab_ready: "तैयार",
    tab_completed: "पुराने",
    dispatch_order: "ऑर्डर भेजें",
    route_compat: "इलाका अनुकूलता",
    recent_orders: "हाल के ऑर्डर",
    sales_trend: "बिक्री का रुझान (पिछले 7 दिन)",
    no_recent_orders: "कोई हाल का ऑर्डर नहीं",
    all_items: "सभी उत्पाद",
    my_items: "मेरे उत्पाद",
    add_product: "नया उत्पाद जोड़ें",
    search_items: "उत्पाद खोजें...",
    edit_product: "उत्पाद संपादित करें",
    edit: "संपादित करें",
    save_changes: "बदलाव सहेजें",
    cancel: "रद्द करें",
    name: "उत्पाद का नाम",
    category: "श्रेणी",
    price: "बिक्री मूल्य (₹)",
    mrp: "एमआरपी (₹)",
    stock: "स्टॉक स्तर",
    description: "विवरण",
    image: "छवि यूआरएल",
    upload: "अपलोड",
    delete: "हटाएं",
    order_id: "ऑर्डर आईडी",
    items: "उत्पाद",
    delivery_address: "डिलीवरी का पता",
    instructions: "निर्देश",
    accept: "स्वीकार करें",
    reject: "अस्वीकार करें",
    mark_ready: "तैयार चिह्नित करें",
    no_orders: "इस खंड में कोई ऑर्डर नहीं है",
    order_details: "ऑर्डर विवरण",
    store_timings: "दुकान का समय",
    store_details: "दुकान का विवरण",
    phone: "फ़ोन",
    email: "ईमेल",
    address: "पता",
    save_store_details: "विवरण सहेजें",
    saving: "सहेजा जा रहा है...",
    total_spent: "कुल खर्च",
    customer_since: "ग्राहक तिथि",
    no_customers: "कोई ग्राहक नहीं मिला।",
    loading_sessions: "सत्र क्रेडेंशियल लोड हो रहे हैं...",
    store_review_pending: "स्टोर समीक्षा लंबित",
    review_pending_message: "आपकी मर्चेंट प्रोफ़ाइल प्लेटफ़ॉर्म सत्यापन की प्रतीक्षा में है। आप कैटलॉग, समय और सेटिंग बदल सकते हैं, लेकिन स्वीकृति तक ग्राहक ऑर्डर प्रतिबंधित रहेंगे।",
    workspace_error_title: "आपका कार्यक्षेत्र नहीं खुल सका",
    workspace_error_desc: "आपका डेटा सुरक्षित है। ऐप रीफ़्रेश करके दोबारा प्रयास करें।",
    refresh_app: "ऐप रीफ़्रेश करें",
    preparing_workspace: "आपका कार्यक्षेत्र तैयार हो रहा है",
    syncing_shop_data: "दुकान का डेटा सुरक्षित रूप से सिंक हो रहा है।",
    shop_partner: "दुकान पार्टनर",
    shopkeeper_partner: "दुकानदार पार्टनर",
    notifications: "दुकान की सूचनाएं",
    no_notifications: "कोई नई सूचना नहीं",
    mark_all_read: "सभी को पढ़ा हुआ करें",
    analytics: "विश्लेषण",
    inventory: "स्टॉक प्रबंधन",
    reviews: "समीक्षाएं",
    offers: "ऑफ़र",
    login_title: "किराना पार्टनर पोर्टल",
    login_subtitle: "ऑर्डर स्वीकार करें, स्टॉक संभालें और स्थानीय बिक्री बढ़ाएं।",
    signin_unavailable: "साइन-इन उपलब्ध नहीं है",
    signin_unavailable_desc: "इस ऐप में सुरक्षित Firebase कॉन्फ़िगरेशन उपलब्ध नहीं है। कृपया प्रशासक से संपर्क करें।",
    firebase_online: "Firebase ऑनलाइन है",
    firebase_online_desc: "SMS कोड Google Firebase Authentication से सुरक्षित रूप से भेजे जाएंगे।",
    owner_mobile: "मालिक का मोबाइल नंबर",
    request_code: "OTP कोड भेजें",
    requesting_code: "कोड भेजा जा रहा है...",
    enter_otp: "6 अंकों का OTP दर्ज करें",
    sms_sent_to: "सत्यापन SMS {{phone}} पर भेजा गया",
    back: "वापस",
    verifying: "सत्यापन हो रहा है...",
    verify_continue: "सत्यापित करें और आगे बढ़ें",
    login_agreement: "लॉगिन करके आप सहमत होते हैं",
    merchant_terms: "मर्चेंट शर्तों",
    privacy_policy: "गोपनीयता नीति",
    and: "और",
    error_invalid_phone: "कृपया सही 10 अंकों का मोबाइल नंबर दर्ज करें।",
    error_signin_not_configured: "सुरक्षित साइन-इन कॉन्फ़िगर नहीं है। कृपया सहायता से संपर्क करें।",
    error_security_init: "सुरक्षा सत्यापन शुरू नहीं हो सका। रीफ़्रेश करके दोबारा प्रयास करें।",
    otp_sent: "OTP कोड {{phone}} पर सफलतापूर्वक भेजा गया",
    error_send_otp: "OTP नहीं भेजा जा सका। कृपया विवरण जांचें।",
    error_sms: "SMS भेजते समय समस्या हुई।",
    error_full_otp: "कृपया पूरा 6 अंकों का OTP दर्ज करें।",
    login_success: "सफलतापूर्वक लॉगिन हो गया!",
    error_invalid_otp: "OTP गलत है। कृपया दोबारा प्रयास करें।",
    error_verification: "सत्यापन विफल रहा।",
    daily_target: "दैनिक लक्ष्य: ₹5,000",
    requires_action: "कार्रवाई आवश्यक",
    manage_inventory: "स्टॉक में प्रबंधित करें",
    sales_progress: "पिछले 7 दिनों की बिक्री प्रगति",
    quick_refill: "त्वरित स्टॉक भराई",
    quick_refill_desc: "कम स्टॉक वाले उत्पाद एक टैप में भरें",
    quick_utilities: "त्वरित सुविधाएं",
    view_orders: "ऑर्डर देखें",
    manage_catalog: "कैटलॉग संभालें",
    order_status_mix: "ऑर्डर स्थिति सारांश",
    order_status_mix_desc: "दुकान के ऑर्डर पूरे होने का सारांश",
    latest_orders_desc: "तीन नवीनतम ग्राहक ऑर्डर",
    healthy_stock: "पर्याप्त स्टॉक",
    low_stock_alert: "कम स्टॉक चेतावनी",
    hidden_items: "छिपे उत्पाद",
    inventory_title: "स्टॉक प्रबंधन",
    inventory_subtitle: "लाइव स्टॉक, बदलाव और समायोजन देखें",
    stock_correction: "मैन्युअल स्टॉक सुधार",
    stock_correction_desc: "उत्पाद का स्टॉक तुरंत बढ़ाएं या घटाएं",
    select_product: "उत्पाद चुनें",
    choose_item: "उत्पाद चुनें...",
    correction_type: "सुधार का प्रकार",
    quantity: "मात्रा",
    correction_note: "सुधार नोट",
    correction_note_placeholder: "उदाहरण: नया स्टॉक आया या डिब्बा खराब था",
    stock_ledger: "स्टॉक सूची संदर्भ",
    search_item: "उत्पाद खोजें...",
    add_units: "{{count}} यूनिट जोड़ें",
    reduce_unit: "1 यूनिट घटाएं",
    movement_logs: "स्टॉक बदलाव और समायोजन रिकॉर्ड",
    movement_logs_desc: "उत्पाद जोड़ने, बिक्री और रीफिल का लाइव रिकॉर्ड",
    no_stock_logs: "अभी कोई स्टॉक बदलाव दर्ज नहीं है।",
    restock: "नया स्टॉक",
    sale: "बिक्री",
    return_stock: "वापसी",
    damaged: "खराब",
    analytics_title: "दुकान प्रदर्शन विश्लेषण",
    analytics_subtitle: "आय, ग्राहक, औसत ऑर्डर और रिपोर्ट देखें",
    monthly_sales: "मासिक बिक्री",
    weekly_sales: "साप्ताहिक बिक्री",
    average_order_value: "औसत ऑर्डर मूल्य",
    customer_retention: "ग्राहक वापसी दर",
    sales_by_category: "श्रेणी के अनुसार बिक्री",
    sales_by_category_desc: "मुख्य विभागों की आय का विवरण (₹)",
    peak_hours: "सबसे व्यस्त ऑर्डर समय",
    peak_hours_desc: "ग्राहक चेकआउट समय का रुझान",
    top_products: "सबसे अधिक बिकने वाले उत्पाद",
    top_products_desc: "स्टॉक में सबसे अधिक बिकने वाले उत्पाद",
    slow_products: "धीमे बिकने वाले उत्पाद",
    slow_products_desc: "स्टॉक में सबसे कम बिकने वाले उत्पाद",
    download_report: "रिपोर्ट डाउनलोड करें",
    no_data: "दिखाने के लिए डेटा नहीं है।",
    search_customers: "नाम या फ़ोन से ग्राहक खोजें...",
    last_purchase: "अंतिम खरीद",
    favourites: "पसंदीदा",
    vip: "वीआईपी",
    shop_specials: "दुकान के विशेष ऑफ़र",
    shop_specials_desc: "नियमित ग्राहकों को इनाम दें, सेल, BOGO या सदस्यता योजना चलाएं।",
    no_specials: "कोई विशेष ऑफ़र नहीं",
    no_specials_desc: "सेल, लॉयल्टी इनाम, BOGO या सदस्यता योजना बनाएं।",
    create_special: "विशेष ऑफ़र बनाएं",
    delete_special_confirm: "यह विशेष ऑफ़र स्थायी रूप से हटाएं?",
    benefit: "लाभ",
    audience: "ग्राहक समूह",
    everyone: "सभी ग्राहक",
    selected_customers: "चुने हुए ग्राहक",
    create_shop_special: "दुकान का विशेष ऑफ़र बनाएं",
    offer_auto_apply: "योग्य सर्वोत्तम ऑफ़र चेकआउट पर अपने आप लागू होगा।",
    close: "बंद करें",
    special_type: "विशेष ऑफ़र प्रकार",
    title: "शीर्षक",
    minimum_order: "न्यूनतम ऑर्डर",
    customer_description: "ग्राहक को दिखने वाला विवरण",
    percentage: "प्रतिशत",
    flat_amount: "निश्चित राशि",
    free_delivery: "मुफ़्त डिलीवरी",
    maximum_saving: "अधिकतम बचत",
    customer_buys: "ग्राहक खरीदे",
    customer_gets_free: "ग्राहक को मुफ़्त मिले",
    eligible_products: "योग्य उत्पाद",
    select_loyal_customers: "नियमित ग्राहक चुनें",
    customers_after_order: "ऑर्डर करने के बाद ग्राहक यहां दिखाई देंगे।",
    plan_price: "योजना मूल्य",
    billing_period: "बिलिंग अवधि",
    monthly: "मासिक",
    quarterly: "त्रैमासिक",
    starts: "शुरू",
    ends: "समाप्त",
    publish_special: "विशेष ऑफ़र प्रकाशित करें",
    public_sale: "सार्वजनिक सेल",
    loyalty_reward: "लॉयल्टी इनाम",
    bogo_deal: "एक खरीदें, एक मुफ़्त",
    subscription_plan: "सदस्यता योजना",
    setup_store: "अपनी दुकान सेट करें",
    setup_subtitle: "ग्राहकों के लिए खोलने से पहले दुकान और स्टॉक का सही विवरण जोड़ें।",
    step_shop: "चरण 1 · दुकान विवरण",
    step_inventory: "चरण 2 · स्टॉक",
    shop_logo: "दुकान का लोगो",
    shop_cover: "दुकान की कवर छवि",
    supported_images: "JPEG और PNG फ़ॉर्मेट समर्थित हैं",
    shop_name: "दुकान का नाम",
    owner_name: "मालिक का नाम",
    owner_phone: "मालिक का फ़ोन नंबर",
    shop_coordinates: "दुकान के भौतिक निर्देशांक",
    coordinates_desc: "दूरी की स्वतः गणना के लिए आवश्यक",
    detect_location: "वर्तमान स्थान पहचानें",
    detecting_location: "स्थान पहचाना जा रहा है...",
    latitude: "अक्षांश",
    longitude: "देशांतर",
    gps_not_set: "GPS निर्देशांक सेट नहीं हैं। दुकान की लाइव स्थिति लेने के लिए स्थान पहचानें दबाएं।",
    customer_store_preview: "ग्राहक को दिखने वाला लाइव स्टोर कार्ड",
    continue_inventory: "स्टॉक कैटलॉग सेटअप पर जाएं",
    product_cover: "उत्पाद कवर छवि",
    tap_upload_cover: "कवर अपलोड करने के लिए टैप करें",
    complete_setup: "सेटअप पूरा करें और दुकान खोलें",
    error_shop_details: "कृपया चरण 1 में दुकान का पूरा विवरण भरें।",
    error_add_product: "दुकान खोलने से पहले स्टॉक सहित कम से कम एक उत्पाद जोड़ें।",
    error_location_required: "सही GPS स्थान आवश्यक है। कृपया दुकान का स्थान कैप्चर करें।",
    cancel_setup_confirm: "सेटअप रद्द करके लॉगआउट करें?",
    error_shop_first: "कृपया पहले दुकान का विवरण पूरा करें।",
    error_store_fields: "कृपया दुकान के सभी आवश्यक विवरण भरें।",
    call_customer: "ग्राहक को कॉल करें",
    whatsapp_customer: "ग्राहक को WhatsApp संदेश भेजें",
    delivery_location: "डिलीवरी स्थान",
    reject_order: "ऑर्डर अस्वीकार करें",
    reject_order_confirm: "क्या आप यह ऑर्डर अस्वीकार करना चाहते हैं?",
    selection: "चयन",
    select_rider: "डिलीवरी पार्टनर चुनें",
    rider_earnings: "राइडर कमाई",
    estimated_route: "अनुमानित यात्रा",
    nearest_stop_order: "निकटतम स्टॉप क्रम",
    batch_created: "डिलीवरी बैच बनाकर {{name}} को सौंप दिया गया।",
    create_delivery_batch: "डिलीवरी बैच बनाएं",
    selected_orders: "चुने हुए ऑर्डर",
    subtotal: "उप-योग",
    total: "कुल",
    payment: "भुगतान",
    customer: "ग्राहक",
    decrease_stock: "स्टॉक घटाएं",
    increase_stock: "स्टॉक बढ़ाएं",
    delete_product: "उत्पाद हटाएं",
    delete_product_confirm: "यह उत्पाद स्थायी रूप से हटाएं?",
    no_items_found: "कोई उत्पाद नहीं मिला",
    product_main_image: "उत्पाद की मुख्य छवि",
    product_gallery: "उत्पाद गैलरी छवियां",
    delete_image: "छवि हटाएं",
    store_availability: "दुकान की उपलब्धता",
    store_availability_desc: "दुकान तुरंत खोलें या बंद करें",
    store_branding: "दुकान ब्रांडिंग",
    shop_logo_image: "दुकान का लोगो",
    store_cover_banner: "दुकान का कवर बैनर",
    theme_style: "ऐप थीम शैली",
    theme_style_desc: "लाइट (दिन) या डार्क (रात) मोड चुनें",
    shop_parameters: "दुकान के मापदंड",
    closing_time: "बंद होने का समय",
    opening_time: "खुलने का समय",
    delivery_radius: "डिलीवरी सीमा (किमी)",
    legal_policies: "कानूनी और नीतियां",
    merchant_terms_conditions: "मर्चेंट नियम और शर्तें",
    merchant_privacy_policy: "मर्चेंट गोपनीयता नीति",
    customer_reviews: "ग्राहक समीक्षाएं",
    reviews_subtitle: "ग्राहक संतुष्टि समझें, समीक्षा का उत्तर दें और रेटिंग संभालें",
    no_reviews: "कोई समीक्षा प्राप्त नहीं हुई",
    no_reviews_desc: "पूर्ण ऑर्डर के बाद ग्राहक समीक्षाएं यहां दिखाई देंगी।",
    report_review: "नकली समीक्षा की रिपोर्ट करें",
    merchant_reply: "मर्चेंट उत्तर",
    write_reply: "इस समीक्षा का उत्तर लिखें...",
    reply: "उत्तर दें",
    reporting_reason: "रिपोर्ट करने का कारण",
    reporting_placeholder: "नकली रेटिंग, प्रतिस्पर्धी दुरुपयोग या आपत्तिजनक भाषा...",
    submit_report: "रिपोर्ट जमा करें",
    rating: "रेटिंग",
    save: "सहेजें",
    light: "लाइट",
    dark: "डार्क",
    versus_last_month: "पिछले महीने से +8.2%",
    estimated_weekly_receipts: "अनुमानित साप्ताहिक प्राप्तियां",
    per_checkout: "प्रति पूर्ण कार्ट",
    this_quarter: "इस तिमाही में +2.5%",
    complete_orders_for_insights: "सबसे अधिक बिकने वाले उत्पाद देखने के लिए ऑर्डर पूरे करें।",
    units_checked_out: "{{count}} यूनिट खरीदी गईं",
    catalog_moving_well: "सभी कैटलॉग उत्पाद अच्छी गति से बिक रहे हैं।",
    item_count: "{{count}} उत्पाद",
    units_in_stock: "स्टॉक में {{count}}",
    units: "{{count}} यूनिट",
    add: "जोड़ें",
    reduce: "घटाएं",
    quantity_example: "उदाहरण: 10",
    adjusting: "बदलाव हो रहा है...",
    execute_correction: "स्टॉक सुधार लागू करें",
    cannot_reduce_stock: "स्टॉक {{amount}} कम नहीं किया जा सकता। वर्तमान स्टॉक केवल {{stock}} है।",
    manual_correction_note: "मैनुअल स्टॉक सुधार",
    updated_by: "अपडेट करने वाला",
    public_sale_desc: "सभी ग्राहकों के लिए प्रतिशत या निश्चित छूट।",
    loyalty_reward_desc: "आपके चुने हुए ग्राहकों के लिए निजी नियमित लाभ।",
    bogo_desc: "एक खरीदें एक मुफ्त और उत्पाद-विशिष्ट लाभ।",
    subscription_desc: "मासिक या त्रैमासिक सदस्यता योजना प्रकाशित करें।",
    offer_error_title: "स्पष्ट शीर्षक और ग्राहक के लिए विवरण जोड़ें।",
    offer_error_date: "समाप्ति तिथि आरंभ तिथि के बाद या समान होनी चाहिए।",
    offer_error_percent: "प्रतिशत छूट 1% से 90% के बीच होनी चाहिए।",
    offer_error_flat: "निश्चित छूट ₹0 से अधिक होनी चाहिए।",
    offer_error_customer: "कम से कम एक वफादार ग्राहक चुनें।",
    offer_error_product: "BOGO ऑफ़र के लिए कम से कम एक उत्पाद चुनें।",
    offer_error_subscription: "सदस्यता मूल्य ऋणात्मक नहीं हो सकता।",
    offer_error_create: "यह दुकान ऑफ़र नहीं बनाया जा सका।",
    month: "माह",
    quarter: "तिमाही",
    subscription_benefit: "₹{{price}}/{{period}} · सदस्यों को {{value}}% बचत",
    percent_off: "{{value}}% छूट",
    percent_off_upto: "{{value}}% छूट, अधिकतम ₹{{max}}",
    flat_off: "₹{{value}} की छूट",
    buy_get_free: "{{buy}} खरीदें, {{get}} मुफ्त पाएं",
    active: "सक्रिय",
    expired: "समाप्त",
    paused: "रुका हुआ",
    shop_special: "दुकान ऑफ़र",
    selected_count: "{{count}} चुने गए",
    members: "सदस्य",
    to: "से",
    offer_title_placeholder: "सप्ताहांत किराना सेल",
    offer_desc_placeholder: "अपने रोज़मर्रा के घरेलू सामान पर बचत करें।",
    percent: "प्रतिशत",
    value: "मूल्य",
    customer_order_spend: "{{orders}} ऑर्डर · ₹{{spent}} खर्च",
    product_name_placeholder: "उदाहरण: ताज़ी ब्रेड (400 ग्राम)",
    product_desc_placeholder: "उत्पाद का आकार, पैकेज और अन्य विवरण...",
    cat_groceries: "किराना सामान",
    cat_snacks_beverages: "स्नैक्स और पेय",
    cat_medical: "मेडिकल / फार्मेसी",
    cat_electronics: "इलेक्ट्रॉनिक्स",
    cat_stationery: "स्टेशनरी",
    cat_fashion: "फैशन",
    cat_books: "किताबें और नवीन वस्तुएं",
    cat_home_essentials: "घरेलू आवश्यक सामान",
    cat_pet_supplies: "पालतू पशु सामान",
    cat_beauty: "सौंदर्य और व्यक्तिगत देखभाल",
    geolocation_unsupported: "यह डिवाइस लोकेशन का समर्थन नहीं करता।",
    price_above_mrp: "बिक्री मूल्य (₹{{price}}) एमआरपी (₹{{mrp}}) से अधिक नहीं हो सकता।",
    product_upload_failed: "{{name}} की तस्वीर अपलोड नहीं हो सकी। दोबारा प्रयास करें।",
    setup_failed: "दुकान सेटअप विफल: {{error}}",
    store_onboarding: "दुकान पंजीकरण",
    store_onboarding_desc: "अपनी दुकान पोर्टल प्रोफ़ाइल सेट करें",
    step_one: "चरण 1",
    step_two: "चरण 2",
    add_inventory: "स्टॉक जोड़ें",
    provide_store_details: "दुकान प्रोफ़ाइल का विवरण दें",
    store_logo_banner: "दुकान लोगो / बैनर",
    tap_upload_store_logo: "दुकान का लोगो या बैनर अपलोड करें",
    shop_name_placeholder: "उदाहरण: फ्रेश चॉइस किराना",
    store_category: "दुकान की श्रेणी",
    full_address: "पूरा भौतिक पता",
    address_placeholder: "उदाहरण: दुकान नंबर 15, भूतल, मुख्य बाजार",
    my_kirana_store: "मेरी किराना दुकान",
    store_location_address: "दुकान का पता",
    add_initial_products: "कैटलॉग में शुरुआती उत्पाद जोड़ें",
    add_initial_products_desc: "ग्राहक चेकआउट चालू करने के लिए कम से कम एक उत्पाद और उसका स्टॉक जोड़ें।",
    initial_product_placeholder: "उदाहरण: ताज़े सेब (1 किग्रा)",
    price_example: "उदाहरण: 90",
    mrp_example: "उदाहरण: 100",
    initial_stock: "शुरुआती स्टॉक",
    stock_example: "उदाहरण: 50",
    calculated_discount: "ग्राहक छूट: एमआरपी पर {{value}}% की बचत।",
    product_cover_optional: "उत्पाद कवर तस्वीर (वैकल्पिक)",
    add_item_inventory: "उत्पाद स्टॉक में जोड़ें",
    added_catalog: "जोड़े गए उत्पाद ({{count}})",
    no_initial_items: "अभी कोई उत्पाद नहीं जोड़ा गया। ऊपर का फॉर्म भरकर उत्पाद जोड़ें।",
    return_dashboard: "डैशबोर्ड पर लौटें",
    merchant_owner: "दुकान मालिक",
    store_settings: "दुकान सेटिंग",
    business_reports: "व्यापार रिपोर्ट",
    sign_out: "साइन आउट",
    no_recent_alerts: "कोई हाल की चेतावनी या सूचना नहीं है।"
  }
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  locale: 'en-IN' | 'hi-IN';
  t: (key: string, params?: TranslationParams) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('shop_app_preferred_language');
    return (saved === 'hi' ? 'hi' : 'en') as Language;
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('shop_app_preferred_language', lang);
  };

  useEffect(() => {
    document.documentElement.lang = language === 'hi' ? 'hi-IN' : 'en-IN';
  }, [language]);

  const t = (key: string, params: TranslationParams = {}) => {
    const dictionary = translations[language] as Record<string, string>;
    const fallback = translations.en as Record<string, string>;
    const template = dictionary[key] || fallback[key] || String(key);
    return Object.entries(params).reduce((text, [name, value]) => text.replaceAll(`{{${name}}}`, String(value)), template);
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, locale: language === 'hi' ? 'hi-IN' : 'en-IN', t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
