const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('fs');const vm=require('vm');const ts=require('typescript');const path=require('path');
function harness({failPhoto=false,failCommit=false}={}) {
 const values=[],deps=[];let cursor=0;const effects=[],records=new Map(),published=[],uploads=[],drafts=[];
 const user={uid:'owner-test',fullName:'Test Owner',phone:'+919800000001',role:'owner'};
 const photo={name:'store.jpg'};
 const saved={setupId:'shop-stable',step:2,shopName:'Saved Store',shopCategories:['groceries','stationery'],shopAddress:'Saved address',openingTime:'09:00',closingTime:'21:00',deliveryRadius:4,shopImageFile:photo,latitude:26.7,longitude:83.3,prodName:'',prodDescription:'',prodPrice:'',prodMrp:'',prodStock:'',prodCategory:'groceries',prodImageFile:null,prodImagePreview:'',productsList:[{id:'product-stable',name:'Rice',description:'Saved description',price:50,mrp:60,stock:9,category:'groceries',imageFile:{name:'rice.jpg'},imagePreview:''}]};
 const react={createElement:(type,props,...children)=>({type,props:{...props,children}}),useState:initial=>{const i=cursor++;if(!(i in values))values[i]=initial;return [values[i],v=>values[i]=typeof v==='function'?v(values[i]):v];},useRef:initial=>{const i=cursor++;return values[i]??(values[i]={current:initial});},useEffect:(fn,next)=>{const i=cursor++;if(!deps[i]||next.some((v,j)=>!Object.is(v,deps[i][j]))){deps[i]=next;effects.push(fn);}}};
 const store=()=>({user,logoutOwner:async()=>{}});store.setState=v=>published.push(v);store.getState=()=>({syncAppData:async()=>{}});
 const modules={react,'react-router-dom':{useNavigate:()=>()=>{}},'lucide-react':{},'../lib/withDeadline':{withDeadline:p=>p},'../core/store/useAppStore':{useAppStore:store},'../context/LanguageContext':{useLanguage:()=>({t:(key,vars)=>key+(vars?.error||'')})},'../components/ProductSuggestions':()=>null,'../infrastructure/firebase/firebase':{db:{}},'../infrastructure/repositories/productRepository':{mapFirestoreDocToProduct:(id,data)=>({id,...data})},'../infrastructure/repositories/shopRepository':{shopRepository:{createShop:async(id,data)=>records.set('shops/'+id,data),updateShop:async(id,data)=>records.set('shops/'+id,data)}},'../infrastructure/storage/localStorage':{uploadFile:async(p)=>{uploads.push(p);if(failPhoto)throw Error('upload failure');return 'https://images.test/'+p;}},'../lib/setupDraft':{pendingSetupKey:u=>'draft:'+u,readSetupDraft:async()=>saved,saveSetupDraft:async(u,d)=>drafts.push(d),clearSetupDraft:async()=>{}},'firebase/firestore':{doc:(_,collection,id)=>collection+'/'+id,writeBatch:()=>{const writes=[];return {set:(key,data)=>writes.push([key,data]),update:(key,data)=>writes.push([key,data]),commit:async()=>{if(failCommit)throw Error('commit failure');for(const [key,data] of writes)records.set(key,data);}};}}};
 const source=fs.readFileSync(path.join(__dirname,'../src/pages/Onboarding.tsx'),'utf8');const js=ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.CommonJS,jsx:ts.JsxEmit.React,esModuleInterop:true}}).outputText;
 const exports={};vm.runInNewContext(js,{exports,require:n=>{assert.ok(n in modules,n);return modules[n];},crypto:{randomUUID:()=> 'new-id'},URL:{createObjectURL:f=>'blob:'+f.name},navigator:{onLine:true},localStorage:{setItem(){},removeItem(){}},window:{location:{reload(){}}},alert:()=>{}});
 function render(){cursor=0;return exports.default();}
 function find(node,predicate){if(!node||typeof node!=='object')return;if(predicate(node))return node;for(const child of (node.props?.children||[]).flat(Infinity)){const match=find(child,predicate);if(match)return match;}}
 return {records,published,uploads,drafts,async complete(){render();for(const fn of effects.splice(0))fn();await new Promise(resolve=>setImmediate(resolve));const tree=render();for(const fn of effects.splice(0))fn();const button=find(tree,n=>n.type==='button'&&JSON.stringify(n.props.children).includes('complete_setup'));assert.ok(button);await button.props.onClick();}};
}
test('restored initial setup saves every field/photo/product and publishes catalogue immediately',async()=>{const h=harness();await h.complete();const product=h.records.get('products/product-stable');assert.equal(product.shopId,'shop-stable');assert.equal(product.price,50);assert.equal(product.stock,9);assert.equal(product.description,'Saved description');assert.ok(product.image.endsWith('cover.jpg'));assert.equal(h.records.get('shops/shop-stable').address,'Saved address');assert.ok(h.records.get('shops/shop-stable').logoUrl.endsWith('logo.png'));assert.equal(h.records.get('merchants/owner-test').shopId,'shop-stable');assert.equal(h.published[0].products[0].id,'product-stable');assert.equal(h.drafts[0].setupId,'shop-stable');assert.equal(h.drafts[0].shopImageFile.name,'store.jpg');});
for(const failure of ['failPhoto','failCommit'])test(failure+' retains setup and does not enter empty dashboard',async()=>{const h=harness({[failure]:true});await h.complete();assert.equal(h.published.length,0);assert.equal(h.records.has('merchants/owner-test'),false);assert.equal(h.drafts[0].productsList.length,1);});
