import { useEffect, useState } from 'react';
import { adminService } from '../services/adminService';
interface Request { id:string; uid:string; accountType:string; status:string; requestedAt:string; blockers:string[]; lastErrorCode?:string }
interface Detail { request:Request; uid:string; blockers:string[]; orders:{id:string;status:string}[]; shops:{id:string;status:string}[]; financialRecords:{path:string;status:string}[]; reviewWarning:string }
export default function AccountDeletion() {
  const [requests,setRequests]=useState<Request[]>([]), [detail,setDetail]=useState<Detail|null>(null);
  const [error,setError]=useState(''), [busy,setBusy]=useState(false), [evidence,setEvidence]=useState(''), [confirmed,setConfirmed]=useState(false);
  async function load(){setError('');try{setRequests((await adminService.deletionRequests()).requests);}catch(e){setError(e instanceof Error?e.message:'Unable to load requests');}}
  useEffect(()=>{void load();},[]);
  async function select(id:string){setBusy(true);setError('');setDetail(null);setConfirmed(false);setEvidence('');try{setDetail(await adminService.deletionRequests(id));}catch(e){setError(e instanceof Error?e.message:'Unable to inspect request');}finally{setBusy(false);}}
  async function approve(){if(!detail || !confirmed)return;setBusy(true);setError('');try{await adminService.approveDeletion(detail.request.id,evidence);setDetail(null);await load();}catch(e){setError(e instanceof Error?e.message:'Approval failed');}finally{setBusy(false);}}
  return <div className="space-y-5"><h1 className="text-2xl font-bold">Account deletion requests</h1><p>Review verified requests, settlements and retention before approving irreversible cleanup. The queue shows up to 100 outstanding requests. Approved jobs run on the configured deletion scheduler.</p>
    {error&&<p role="alert" className="rounded-xl bg-red-50 p-4 text-red-700">{error}</p>}<button disabled={busy} onClick={()=>void load()} className="rounded-xl border p-3">Refresh queue</button>
    <div className="grid gap-5 lg:grid-cols-2"><section className="space-y-3" aria-label="Outstanding requests">{requests.length===0&&<p>No outstanding requests loaded.</p>}{requests.map(r=><button key={r.id} disabled={busy} onClick={()=>void select(r.id)} className="block w-full break-all rounded-xl border p-4 text-left"><strong>{r.accountType} · {r.status}</strong><p>{r.uid}</p><p>{r.requestedAt}</p>{r.lastErrorCode&&<p className="text-red-600">Cleanup needs retry: {r.lastErrorCode}</p>}</button>)}</section>
    {detail&&<section className="space-y-4 rounded-xl border p-5"><h2 className="text-xl font-bold">Review {detail.request.accountType} deletion</h2><p className="break-all">Identity: {detail.uid}</p><p>{detail.reviewWarning}</p><h3 className="font-bold">Current blockers</h3><ul>{detail.blockers.map(b=><li key={b}>{b}</li>)}</ul><details><summary>Orders, shops and financial references</summary><pre className="whitespace-pre-wrap break-all text-xs">{JSON.stringify({orders:detail.orders,shops:detail.shops,financialRecords:detail.financialRecords},null,2)}</pre></details><label className="block">Review evidence reference (ticket or reconciliation ID; no personal data)<input value={evidence} onChange={e=>setEvidence(e.target.value)} maxLength={160} className="mt-2 w-full rounded-xl border bg-transparent p-3" /></label><label className="flex gap-3"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)} /><span>I verified actual payouts, refunds, disputes, legal holds and document retention. There are no unresolved obligations preventing deletion or requiring retention of the personal files that this cleanup removes. I approve permanent cleanup.</span></label><button disabled={busy||!confirmed||evidence.trim().length<5||detail.blockers.length>0||['PROCESSING','APPROVED'].includes(detail.request.status)} onClick={()=>void approve()} className="rounded-xl bg-red-700 px-5 py-3 font-bold text-white disabled:opacity-40">Approve permanent deletion</button></section>}</div></div>;
}
